services:
  - type: web
    name: rutube
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python rutube.py
    envVars:
      - key: BOT_TOKEN
        value: 8476332708:AAGxLQqGqRidMZwfa_5C2Mx5B0efrVkyxpo
    build:
      pythonVersion: 3.11
